name: Create release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - name: install dependencies
        run: npm ci
      - name: build
        run: npx tsc
      - name: create archive
        run: tar czf depths-of-the-mind.tar.gz dist/ images/ sounds/ index.html style.css
      - uses: softprops/action-gh-release@v0.1.5
        with:
          files:
            depths-of-the-mind.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
